application: nest
version: 1
runtime: python
api_version: 1

handlers:
- url: /api/.*
  script: code.py
- url: /optimized/.*
  script: code.py
- url: /text/.*
  script: code.py
- url: /image/.*
  script: code.py
- url: /
  static_files: index.html
  upload: index.html